version: '3.9'

services:

  ypract-redis:
    image: redis:6-alpine
    container_name: ypract_redis
    volumes:
        - ypract_redis_vol:/data
    ports: 
        - 6379:6379

  ypract-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    container_name: ypract_elasticsearch
    environment:
        - discovery.type=single-node
    ports: 
        - 9200:9200
    profiles:
        - search

  ypract-jaegertracing:
    image: jaegertracing/all-in-one:latest
    container_name: ypract_jaegertracing
    ports:
        - 6831:6831/udp
        - 16686:16686

  ypract-admin-postgres:
    image: postgres:13-alpine
    container_name: ypract_admin_postgres
    environment:
        - POSTGRES_HOST=movies-admin-postgres
        - POSTGRES_PORT=5432
        - POSTGRES_DB=movies
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=superPassword
    volumes:
        - ypract_admin_postgres_vol:/var/lib/postgresql/data
    ports:
        - 5432:5432
    profiles:
        - admin

  ypract-auth-postgres:
    image: postgres:13-alpine
    container_name: ypract_auth_postgres
    environment:
        - POSTGRES_HOST=ypract-auth-postgres
        - POSTGRES_PORT=5432
        - POSTGRES_DB=auth
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=superPassword
    volumes:
        - ypract_auth_postgres_vol:/var/lib/postgresql/data
    ports:
        - 5433:5432
    profiles:
        - auth

  ypract-admin-nginx:
    image: nginx:latest
    container_name: ypract_admin_nginx
    volumes:
        - ./admin/admin_panel/compose/dev/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./admin/admin_panel/compose/dev/nginx/configs:/etc/nginx/conf.d:ro
        - ./admin/admin_panel/movies_admin/static:/data/static
    ports:
        - 80:80
    depends_on:
        - ypract-admin-django
    links:
        - ypract-admin-django:django
    profiles:
        - admin
    restart: always


  ypract-search-api-nginx:
    build: ./api/docker/nginx/
    container_name: ypract_api_nginx
    ports:
        - 88:80
    depends_on:
        - ypract-search-api
    links:
        - ypract-search-api:api
    profiles:
        - search
    restart: always

  ypract-auth-nginx:
    image: nginx:latest
    container_name: ypract_auth_nginx
    volumes:
        - ./auth/compose/dev/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./auth/compose/dev/nginx/configs:/etc/nginx/conf.d:ro
    depends_on:
        - ypract-auth
    ports:
        - "8888:80"
    links:
        - ypract-auth:auth
    profiles:
        - auth
    restart: always

  ypract-pg-es-etl:
    build:
        context: ./etl
        dockerfile: ./compose/etl/Dockerfile
    container_name: ypract_pg_es_etl
    depends_on:
        - ypract-admin-postgres
        - ypract-admin-django
        - ypract-elasticsearch
    env_file:
        - ./etl/.envs/etl.env
    profiles:
        - etl

  ypract-sqlite-pg-etl:
    build:
        context: ./admin/admin_panel
        dockerfile: compose/dev/etl/Dockerfile
    image: ypract_sqlite_pg_etl
    container_name: ypract_sqlite_pg_etl
    command: python load_data.py
    depends_on:
        - ypract-admin-postgres
    env_file:
        - ./admin/admin_panel/.envs/dev/postgres.env
    volumes:
        - ./admin/admin_panel/ypract_sqlite_to_postgres:/app
    links:
        - ypract-admin-postgres:postgres
    profiles:
        - etl

  ypract-admin-django:
    build:
        context: ./admin/admin_panel
        dockerfile: ./compose/dev/django/Dockerfile
    image: ypract_admin_django
    container_name: ypract_admin_django
    command: >
        bash -c "
        python manage.py collectstatic --noinput && 
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000"
    depends_on:
        - ypract-admin-postgres
    env_file:
        - ./admin/admin_panel/.envs/dev/django.env
        - ./admin/admin_panel/.envs/dev/postgres.env
    volumes:
        - ./admin/admin_panel/movies_admin:/app
    ports:
        - 8000:8000
    links:
        - ypract-admin-postgres:postgres
    profiles:
        - admin

  ypract-search-api:
    build:
        context: ./api
        dockerfile: ./docker/api/Dockerfile
    image: ypract_search_api
    container_name: ypract_search_api
    depends_on:
        - ypract-redis
        - ypract-elasticsearch
    ports:
        - "8080:8000"
    links:
        - ypract-elasticsearch:elastic
    profiles:
        - search

  ypract-auth:
    build:
        context: ./auth
        dockerfile: ./compose/dev/auth/Dockerfile
    image: ypract_auth
    container_name: ypract_auth
    command: python app.py
    depends_on:
        - ypract-auth-postgres
        - ypract-redis
    volumes:
        - ./auth/auth:/app/auth
        - ./auth/migrations:/app/migrations
        - ./auth/app.py:/app/app.py:ro
        - ./auth/.envs/dev/auth.env:/app/.env:ro
    ports: 
        - "5000:5000"
    links:
        - ypract-auth-postgres:postgres
    profiles:
        - auth

volumes:
    ypract_redis_vol:
    ypract_auth_postgres_vol:
    ypract_admin_postgres_vol:
